# Generated by Django 5.1.6 on 2025-02-10 04:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(default='Welcome', max_length=100)),
                ('image', models.ImageField(blank=True, default='test.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('username', models.CharField(default='anon', max_length=20, null=True)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='test.jpg', upload_to='')),
                ('dp', models.ImageField(blank=True, default='test.jpg', upload_to='')),
                ('dislikes', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('mins_read', models.IntegerField(default=5)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmark_post', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='App.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='App.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('email', models.EmailField(default='empty', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
