# Generated by Django 5.1.6 on 2025-04-17 22:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dp',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.CharField(blank=True, default='anon', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bio',
            field=models.TextField(blank=True, default='Welcome', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='dp',
            field=cloudinary.models.CloudinaryField(blank=True, default='project-management_gqhk75', max_length=255, null=True, verbose_name='image'),
        ),
    ]
