# Generated by Django 5.1.6 on 2025-02-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='account_verified',
            new_name='is_verified',
        ),
    ]
