# Generated by Django 5.1.6 on 2025-04-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_blog_dp_alter_blog_title_alter_blog_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bio',
            field=models.TextField(blank=True, default='Welcome', max_length=1000, null=True),
        ),
    ]
