# Generated by Django 5.0.7 on 2024-10-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_blog_dislikes_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mins_read',
            field=models.IntegerField(default=5),
        ),
    ]
