# Generated by Django 5.1.6 on 2025-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_category_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bio',
            field=models.TextField(blank=True, default='Welcome', max_length=2000, null=True),
        ),
    ]
