# Generated by Django 5.0.7 on 2024-10-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_blog_mins_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bio',
            field=models.CharField(default='Welcome', max_length=100),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='App.blog')),
            ],
        ),
    ]
