# Generated by Django 5.0.7 on 2024-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_category_bio_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_ccount',
            field=models.IntegerField(default=0),
        ),
    ]
