# Generated by Django 5.0.7 on 2024-10-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_blog_views_ccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views_ccount',
            new_name='views_count',
        ),
    ]
