# Generated by Django 5.0.7 on 2024-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_views_ccount_blog_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='test.jpg', upload_to=''),
        ),
    ]
