# Generated by Django 5.0.7 on 2024-10-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
