# Generated by Django 5.0.7 on 2024-11-30 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_blog_likes_blog_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(default='None', related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
