# Generated by Django 5.0.7 on 2025-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='empty', max_length=100),
        ),
    ]
