# Generated by Django 5.0.7 on 2025-01-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
